
package librarysysdev.GUI.login;


public class LoginView extends javax.swing.JFrame {

  /**
   * Creates new form LoginView
   */
  public LoginView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    loginView = new javax.swing.JPanel();
    userLabel = new javax.swing.JLabel();
    txtUser = new javax.swing.JTextField();
    passwordLabel = new javax.swing.JLabel();
    txtPassword = new javax.swing.JPasswordField();
    loginBtn = new javax.swing.JButton();
    iconLoginView = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Login");

    loginView.setBackground(new java.awt.Color(238, 229, 233));

    userLabel.setBackground(new java.awt.Color(241, 191, 152));
    userLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
    userLabel.setForeground(new java.awt.Color(0, 0, 0));
    userLabel.setText("User");

    txtUser.setBackground(new java.awt.Color(241, 191, 152));
    txtUser.setForeground(new java.awt.Color(0, 0, 0));
    txtUser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtUserActionPerformed(evt);
      }
    });

    passwordLabel.setBackground(new java.awt.Color(241, 191, 152));
    passwordLabel.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
    passwordLabel.setForeground(new java.awt.Color(0, 0, 0));
    passwordLabel.setText("Password");

    txtPassword.setBackground(new java.awt.Color(241, 191, 152));
    txtPassword.setForeground(new java.awt.Color(0, 0, 0));
    txtPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtPasswordActionPerformed(evt);
      }
    });

    loginBtn.setBackground(new java.awt.Color(255, 255, 102));
    loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    loginBtn.setForeground(new java.awt.Color(0, 0, 0));
    loginBtn.setText("Enter");
    loginBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    loginBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        loginBtnActionPerformed(evt);
      }
    });

    iconLoginView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarysysdev/GUI/icons/iconLoginView.png"))); // NOI18N

    javax.swing.GroupLayout loginViewLayout = new javax.swing.GroupLayout(loginView);
    loginView.setLayout(loginViewLayout);
    loginViewLayout.setHorizontalGroup(
      loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(loginViewLayout.createSequentialGroup()
        .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(loginViewLayout.createSequentialGroup()
            .addGap(172, 172, 172)
            .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(61, 61, 61)
            .addComponent(iconLoginView))
          .addGroup(loginViewLayout.createSequentialGroup()
            .addGap(206, 206, 206)
            .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(174, Short.MAX_VALUE))
    );
    loginViewLayout.setVerticalGroup(
      loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(loginViewLayout.createSequentialGroup()
        .addGap(153, 153, 153)
        .addGroup(loginViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(loginViewLayout.createSequentialGroup()
            .addComponent(userLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addComponent(passwordLabel)
            .addGap(3, 3, 3)
            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(iconLoginView, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(15, 15, 15)
        .addComponent(loginBtn)
        .addContainerGap(186, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(loginView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(loginView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
    // TODO add your handling code here:
    String userNameCrendentials = txtUser.getText();
    String passwordCredentials = txtUser.getText();
  }//GEN-LAST:event_loginBtnActionPerformed

  private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
    
  }//GEN-LAST:event_txtUserActionPerformed

  private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
  
  }//GEN-LAST:event_txtPasswordActionPerformed

  /**
   * @param args the command line arguments
   */
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel iconLoginView;
  private javax.swing.JButton loginBtn;
  private javax.swing.JPanel loginView;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtUser;
  private javax.swing.JLabel userLabel;
  // End of variables declaration//GEN-END:variables
}
